[package]

name = "oak"
version = "0.1.0"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

[lib]

name = "oak"
path = "src/liboak/lib.rs"
crate_type = ["dylib"]
plugin = true

[dependencies.oak_runtime]
path = "runtime"
